number1 = int(input("Please enter number1 "))
number2 = int(input("Please enter number2 "))
print(number1>number2)
print(number1<number2)
print(number1>=number2)
print(number1<=number2)
print(number1!=number2)
print(number1==number2)
