#file = open("C:\\Users\\Admin\\Downloads\\SQL_Query.txt","r")
file = open("NewFile.txt.txt","r")
print(f"Before reading {file.tell()}")
#data=file.readlines()
data=file.readline()
print(data)
print(f"After reading {file.tell()}")
data=file.readline()
print(f"After reading {file.tell()}")
