#file = open("C:\\Users\\Admin\\Downloads\\SQL_Query.txt","r")
file = open("NewFile.txt.txt","r")
file.seek(15)
#data=file.readlines()
data=file.readline()
print(data)
print(f"After reading {file.tell()}")
data=file.readline()
print(f"After reading {file.tell()}")
